### ISSUE TITLE
Tell me to install the latest .NET in the application instead of just giving me an error midway through running it without a clue what to do.

### ISSUE THREAD

**Issue by Joshua-Ashton** [joe27g/EnhancedDiscord#49]

**Comment by rauenzi** [comment]
Well it says that in the readme and we don't have direct control over the .net errors

**Comment by Joshua-Ashton** [comment]
You do. You can just try catch it or load dynamically and realize its wrong and then tell me to install latest .NET. :upside_down_face:

**Comment by rauenzi** [comment]
Don't recall using the term feature, but alright. Pull requests are always welcome if you find this such a dire bug.

**Comment by rauenzi** [comment]
@TedsterTech @Joshua-Ashton

**Comment by Joshua-Ashton** [comment]
As you said

> This isn't even my project.

**Comment by rauenzi** [comment]
And as you so politely said:
> So go do that.

**Comment by Leopard1907** [comment]
If that is not your project , why did you reply like that in the first place?

"we don't have direct control over the .net errors"

**Comment by rauenzi** [comment]
I'm a contributor and I'm aware of the time limitations of both myself and the ED creator. At this time, solving this issue (that occurs seldomly and is explained in the readme) is not within our current effort's scope. The way that the installer is currently written we don't control the loading process of the .NET dependency (or try catch every usage), that would take implementation changes.

I'm not denying this is an error or calling it a feature as was facetiously suggested, I'm saying that it's a rare error we are not focusing our efforts on. The application itself (ED) is functioning fine and the fix for the installer is explained in the readme for the few encountering the error.

**Comment by Joshua-Ashton** [comment]
You can easily do 1 big try catch around it or another method I described. This wouldn't take you a lot of time. _**You objectively do have complete control over these and can use every method I suggested.**_ 🤠

**Comment by Joshua-Ashton** [comment]
In fact, for the try catch you'd only need to do it upon the first use of a InteropServices (try catch the first function that uses it) and then just show me an error dialog saying what I have to do there.

**Comment by rauenzi** [comment]
The code does not currently do that, I think I mentioned that so while it is possible, it doesn't currently control the error flow. I think that was a communication error, as I'm referring to the current code and you seem to be directing it to me:

>we don't have direct control over the .net errors

This was meant as we don't have anything in the code handling the errors, as in no controls in place. That's why I followed up by saying that isn't the current loading schema. The only thing we currently have is the note on the readme for the few people that have the error.

Unfortunately, it would take more time than you might think to complete the entire process as the installer would need to be recompiled by the repo owner, after a PR, in order to upload it to the website. The version on the website is actually out of date compared to what is on the repo because he is currently quite busy with other things. Also as I said before, PRs are always welcome. Feel free to use any of the methods you pointed out above, I personally would go with number 4 for better UX than number 1.

Have a nice night!
